# Generated by Django 5.1.5 on 2025-02-21 19:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_apparat_xodimi_boss_rahbar_yil_dasturi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim_Nizomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': "Bo'lim nizomi",
                'verbose_name_plural': "Bo'lim nizomi",
            },
        ),
        migrations.CreateModel(
            name='Principals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='principal_photo/')),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('veb_sayt', models.TextField(blank=True, null=True)),
                ('reception_days', models.TextField(null=True)),
                ('date_of_birth', models.TextField(null=True)),
                ('education', models.TextField(null=True)),
                ('field', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Direktor',
                'verbose_name_plural': 'Direktorlar',
            },
        ),
        migrations.CreateModel(
            name='Qabul_Kunlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=150)),
                ('lunch', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tarkibiy_Tuzilma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Tarkibiy tuzilma',
                'verbose_name_plural': 'Tarkibiy tuzilma',
            },
        ),
    ]
