# Generated by Django 5.1.5 on 2025-02-21 19:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bolim_nizomi_principals_qabul_kunlari_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim_manzili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': "Bo'lim manzili",
                'verbose_name_plural': "Bo'lim manzili",
            },
        ),
        migrations.CreateModel(
            name='Bosh_orinlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Bosh orin',
                'verbose_name_plural': 'Bosh orinlar',
            },
        ),
        migrations.CreateModel(
            name='Kun_Tartibi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=200)),
                ('work_time', models.CharField(max_length=200)),
                ('lunch_time', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Kun tartibi',
                'verbose_name_plural': 'Kun tartibi',
            },
        ),
        migrations.CreateModel(
            name='Talim_Tashkiloti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Talim tashkiloti',
                'verbose_name_plural': 'Talim tashkilotlari',
            },
        ),
    ]
