# Generated by Django 5.1.5 on 2025-02-22 12:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bolim_manzili_bosh_orinlar_kun_tartibi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malaka_Oshirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Malaka oshirish',
                'verbose_name_plural': 'Malaka oshirish',
            },
        ),
        migrations.AddField(
            model_name='bolim_manzili',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bosh_orinlar',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kun_tartibi',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
