# Generated by Django 5.1.5 on 2025-02-22 18:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_malaka_oshirish_bolim_manzili_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birinchi_Sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Birinchi sinf',
                'verbose_name_plural': 'Birinchi sinf',
            },
        ),
        migrations.CreateModel(
            name='Bogchaga_Joylashtirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Bog'chaga joylashtirish",
                'verbose_name_plural': "Bog'chaga joylashtirish",
            },
        ),
        migrations.CreateModel(
            name='Bola_Kuchirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bolani maktabdan kuchirish',
                'verbose_name_plural': 'Bolani maktabdan kuchirish',
            },
        ),
        migrations.CreateModel(
            name='Dars_Ishlanmalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dars ishlanma',
                'verbose_name_plural': 'Dars ishlanmalar',
            },
        ),
        migrations.CreateModel(
            name='Davlat_Dasturlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='davlat_dasturlari/')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Davlat dasturlari',
                'verbose_name_plural': 'Davlat dasturlari',
            },
        ),
        migrations.CreateModel(
            name='Fan_Testlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fan test',
                'verbose_name_plural': 'Fan testlar',
            },
        ),
        migrations.CreateModel(
            name='Imtihon_Materiallari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imtihon materiallari',
                'verbose_name_plural': 'Imtihon materiallari',
            },
        ),
        migrations.CreateModel(
            name='Oquvchilar_Qabul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oquvchilarni maktabga qabul',
                'verbose_name_plural': 'Oquvchilarni maktabga qabul',
            },
        ),
        migrations.CreateModel(
            name='Qabul_Teshirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Bog'chaga qabul navbatni teshirish",
                'verbose_name_plural': "Bog'chaga qabul navbatni teshirish",
            },
        ),
        migrations.CreateModel(
            name='Shahodatnomani_Tiklash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shahodatnomani tiklash',
                'verbose_name_plural': 'Shahodatnomani tiklash',
            },
        ),
        migrations.CreateModel(
            name='Talim_Qonun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Talim qonun',
                'verbose_name_plural': 'Talim qonun',
            },
        ),
        migrations.CreateModel(
            name='Tolovlar_Malumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Bog'cha Tolovlar malumot",
                'verbose_name_plural': "Bog'cha Tolovlar malumot",
            },
        ),
        migrations.CreateModel(
            name='Xorijiy_Fuqarolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xorijiy fuqarolar',
                'verbose_name_plural': 'Xorijiy fuqarolar',
            },
        ),
    ]
