# Generated by Django 5.1.5 on 2025-02-22 19:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_birinchi_sinf_bogchaga_joylashtirish_bola_kuchirish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besh_Tashshabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='faoliyat')),
            ],
            options={
                'verbose_name': 'Besh tashshabus',
                'verbose_name_plural': 'Besh tashshabus',
            },
        ),
        migrations.CreateModel(
            name='Hayat_Qarorlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hayat qarorlari',
                'verbose_name_plural': 'Hayat qarorlari',
            },
        ),
        migrations.CreateModel(
            name='Korrupsia_Qarshi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='faoliyat/')),
            ],
            options={
                'verbose_name': 'Korrupsiya qarshi',
                'verbose_name_plural': 'Korrupsiya qarshi',
            },
        ),
        migrations.CreateModel(
            name='Meyoriy_Hujjatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='normativ_hujjatlar/')),
            ],
            options={
                'verbose_name': "Me'yoriy hujjatlar",
                'verbose_name_plural': "Me'yoriy hujjatlar",
            },
        ),
        migrations.CreateModel(
            name='Prezident_Qarorlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='normativ_hujjatlar/')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prezident qarorlari',
                'verbose_name_plural': 'Prezident qarorlari',
            },
        ),
        migrations.CreateModel(
            name='Talim_Terminlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Talim terminlar',
                'verbose_name_plural': 'Talim terminlar',
            },
        ),
        migrations.CreateModel(
            name='Tuman_Hujjatlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Tuman me'yoriy hujjatlar",
                'verbose_name_plural': "Tuman me'yoriy hujjatlar",
            },
        ),
        migrations.CreateModel(
            name='Video_Galereya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.URLField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='video_galereya_images/')),
            ],
            options={
                'verbose_name': 'Video galereya',
                'verbose_name_plural': 'Video galereya',
            },
        ),
        migrations.AddField(
            model_name='dars_ishlanmalar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dars_ishlanmalari/'),
        ),
        migrations.AddField(
            model_name='fan_testlar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='oqituvchilarga/'),
        ),
        migrations.AlterField(
            model_name='birinchi_sinf',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='bogchaga_joylashtirish',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='bola_kuchirish',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='davlat_dasturlari',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='davlat_dasturlari/'),
        ),
        migrations.AlterField(
            model_name='imtihon_materiallari',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='malaka_oshirish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='malaka_oshirish/'),
        ),
        migrations.AlterField(
            model_name='oquvchilar_qabul',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='qabul_teshirish',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='shahodatnomani_tiklash',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='tolovlar_malumot',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='xorijiy_fuqarolar',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
