# Generated by Django 5.1.5 on 2025-02-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_principals_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='principals',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
