# Generated by Django 5.1.5 on 2025-03-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_dars_ishlanmalar_slug_davlat_dasturlari_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dars_ishlanmalar',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='davlat_dasturlari',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='fan_testlar',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='malaka_oshirish',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
