# Generated by Django 5.1.5 on 2025-03-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_dars_ishlanmalar_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imtihon_materiallari',
            name='yil',
            field=models.TextField(null=True),
        ),
    ]
