# Generated by Django 5.1.5 on 2025-03-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_announcement_video_galereya_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_galereya',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
