# Generated by Django 5.1.5 on 2025-03-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_video_galereya_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='besh_tashshabus',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='meyoriy_hujjatlar',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
