# Generated by Django 5.1.5 on 2025-03-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_besh_tashshabus_slug_meyoriy_hujjatlar_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='korrupsia_qarshi',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='besh_tashshabus',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='meyoriy_hujjatlar',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
