# Generated by Django 5.1.5 on 2025-03-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_korrupsia_qarshi_slug_alter_besh_tashshabus_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korrupsia_qarshi',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
