# Generated by Django 5.1.5 on 2025-03-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_korrupsia_qarshi_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meyoriy_hujjatlar',
            name='slug',
        ),
        migrations.AddField(
            model_name='tuman_hujjatlari',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
