# Generated by Django 5.1.5 on 2025-03-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_meyoriy_hujjatlar_slug_tuman_hujjatlari_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuman_hujjatlari',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
