# Generated by Django 5.1.5 on 2025-03-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_tuman_hujjatlari_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meyoriy_hujjatlar',
            name='image',
        ),
        migrations.AddField(
            model_name='tuman_hujjatlari',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='normativ_hujjatlar/'),
        ),
    ]
