# Generated by Django 5.1.5 on 2025-03-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_leftsidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='principals',
            name='school_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
