# Generated by Django 5.1.5 on 2025-03-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='principals',
            options={'verbose_name': "Ta'lim muassasalari", 'verbose_name_plural': "Ta'lim muassasalari"},
        ),
    ]
