# Generated by Django 5.1.5 on 2025-03-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_principals_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolim_manzili',
            name='school_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
