# Generated by Django 5.1.5 on 2025-03-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_bolim_manzili_school_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bolim_manzili',
            old_name='school_location',
            new_name='bolim_map',
        ),
    ]
