# Generated by Django 5.1.5 on 2025-03-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_school_location_bolim_manzili_bolim_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolim_manzili',
            name='bolim_map',
        ),
    ]
