from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(Post)
admin.site.register(Announcement)
admin.site.register(Photo)
admin.site.register(Boss)
admin.site.register(Yil_Dasturi)
admin.site.register(Rahbar)
admin.site.register(Apparat_Xodimi)
admin.site.register(Tarkibiy_Tuzilma)
admin.site.register(Qabul_Kunlari)
admin.site.register(Bolim_Nizomi)
admin.site.register(Principals)
admin.site.register(Talim_Tashkiloti)
admin.site.register(Kun_Tartibi)
admin.site.register(Bosh_orinlar)
admin.site.register(Bolim_manzili)
admin.site.register(Malaka_Oshirish)
admin.site.register(Dars_Ishlanmalar)
admin.site.register(Fan_Testlar)
admin.site.register(Davlat_Dasturlari)
admin.site.register(Talim_Qonun)
admin.site.register(Imtihon_Materiallari)
admin.site.register(Shahodatnomani_Tiklash)
admin.site.register(Bogchaga_Joylashtirish)
admin.site.register(Qabul_Teshirish)
admin.site.register(Tolovlar_Malumot)
admin.site.register(Birinchi_Sinf)
admin.site.register(Oquvchilar_Qabul)
admin.site.register(Bola_Kuchirish)
admin.site.register(Xorijiy_Fuqarolar)
admin.site.register(Video_Galereya)
admin.site.register(Korrupsia_Qarshi)
admin.site.register(Talim_Terminlar)
admin.site.register(Besh_Tashshabus)
admin.site.register(Prezident_Qarorlari)
admin.site.register(Hayat_Qarorlari)
admin.site.register(Meyoriy_Hujjatlar)
admin.site.register(Tuman_Hujjatlari)